---

- name: Start docker service
  listen: "docker-start"
  ansible.builtin.service:
    name: docker
    state: started

- name: Stop docker service
  listen: "docker-stop"
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Reload docker service
  listen: "docker-reload"
  ansible.builtin.service:
    name: docker
    state: reloaded

- name: Restart docker service
  listen: "docker-restart"
  ansible.builtin.service:
    name: docker
    state: restarted
